### ISSUE TITLE
Add opacity to header

### ISSUE THREAD

**Issue by vivkay** [vivkay/ffi#11]

**Comment by sara-clayton2** [comment]
@thomasbradley 

On all the billboard images on each page we have an opacity overlay of a black color and for some reason even though the color is set to black its appearing white? any way to fix this ?

**Comment by sara-clayton2** [comment]
@thomasjbradley

**Comment by vivkay** [comment]
Hi @thomasjbradley, 

Just to add to this issue, we are using jekyll to populate our images where we have a hero value specified in the yml file. The images are working nicely. 

```
	<header class="hero" role="banner" {% if page.hero %} style="background-image: url({{site.baseurl}}/img/{{page.hero}})" alt="" {% endif %}>
	</header>
```
The issue is with the css; currently we have this:

```
.hero {
    text-align: center;
    max-height: 75vh;
    position: relative;
    background:
            linear-gradient(
            rgba(0, 0, 0, 0.45),
            rgba(0, 0, 0, 0.45)
        ),
        no-repeat center bottom / 100% 80%,
         no-repeat center top;
    background-color: grey;
    background-size: cover;
    padding-top: 46%;
}
```
I assumed it was an issue because we are calling our images from the html file as inline styling, instead of directly from css, so I tried removing the 'style' portion from our header, and adding it right in the css file. But it just made the images disappear (perhaps I typed something incorrectly?) 

```
.hero {
    text-align: center;
    max-height: 75vh;
    position: relative;
    background:
            linear-gradient(
            rgba(0, 0, 0, 0.45),
            rgba(0, 0, 0, 0.45)
        ),
        no-repeat center bottom / 100% 80%,
    url({{site.baseurl}}/img/{{page.hero}});
    background-color: grey;
    background-size: cover;
    padding-top: 46%;
}
```

Any ideas to what we're doing wrong here?

Thanks!!

**Comment by thomasjbradley** [comment]
The code you have near the top is the best way to do it:

```html
<header class="hero" role="banner" {% if page.hero %} style="background-image: url({{site.baseurl}}/img/{{page.hero}})" alt="" {% endif %}>
```

But the problem you're running into is that any CSS you write for `background-image` in your CSS file will be over written by this.

There are two solutions I can think of:

1. Include an empty `<div>` in the header that can be positioned over the image with the black background.
2. Use `::before` or `::after` and position one of them over the image with the black colour.

**Comment by sara-clayton2** [comment]
So i added the ::after and it works for the opacity part. but now the opacity won't move down and is covering the navigation and on top of that when the screen gets smaller all the image just spills out of the banner image ( which I can probably just fix in the media queries I'm assuming ) 
![screen shot 2016-03-04 at 3 24 40 pm](https://cloud.githubusercontent.com/assets/6340308/13539285/79cd9a82-e21d-11e5-99d6-0127c156834e.png)
![screen shot 2016-03-04 at 3 24 20 pm](https://cloud.githubusercontent.com/assets/6340308/13539286/7a82d1f4-e21d-11e5-9a44-807880c540e0.png)
![screen shot 2016-03-04 at 3 24 32 pm](https://cloud.githubusercontent.com/assets/6340308/13539288/7b56e034-e21d-11e5-949d-3470e9a49a05.png)

**Comment by thomasjbradley** [comment]
Try getting rid of the `.banner-opacity` `<div>` and putting the `::after` stuff right onto `.hero`.

**Comment by sara-clayton2** [comment]
I ended up fixing it with a z-index
