### ISSUE TITLE
github sync 

### ISSUE THREAD

**Issue by vivkay** [vivkay/ffi#24]
Hi @thomasjbradley, 

I'm having some issues with Github; for some reason we've merged our files as a team and the changes are showing up on the live url. But when I'm in my local app, I see an old version. Even when I hit 'sync' in the github app, nothing changes. Do I need to re-fork my own repo?

Thanks!

V

**Comment by thomasjbradley** [comment]
Hmm... yeah, that would probably be a good idea.
