### ISSUE TITLE
ghost posts

### ISSUE THREAD

**Issue by vivkay** [vivkay/ffi#29]
Hi @thomasjbradley, 

The strangest thing is happening with my jekyll post loop! I'm using a post loop because it's specifically for the blog page, and we have dated posts. 

The posts are coming in fine with the info from the .md file, but somehow there's an auto-generation of ghost posts also. Somehow these ghost posts are pulling their own titles from the title of the .md file, and then creating their own ul's and li's with blank content. It's giving me the heebie-jeebies! :ghost: :ghost: :ghost:

This is my blog.html file: 
```
<div class="grid">
  {% for post in site.posts %}
  <ul>
    <li class="blog-li">
      <div class="unit unit-xs-1 unit-s-1 unit-m-1-2 unit-l-1-2">
        <img class="blog-thumb" src="{{base.url}}/img/{{post.image}}">
      </div>
      <div class="unit unit-xs-1 unit-s-1 unit-m-1-2 unit-l-1-2">
        <a href="">{{post.title}}</a>
        <p>{{post.author}}</p>
        <p>{{post.meta}}</p>
        <a class="btn-cta" href="#">Read More</a>
      </div>
    </li>
  </ul>
  {% endfor %}
</div>
```
And the md:

```
title: "Jargon Buster: Ecosystem Services"
meta: In the spirit of clear communication, we are starting a series of jargon buster blog posts, which aim to demystify some of the more obscure terms used by the conservation community. In this second instalment, Kristi Foster explains just what we mean by ‘ecosystem services’.
category: general
author: Kristi Foster
image: blog-ecosystem.jpg
```
And here's a screen-cap of what I'm seeing on the page, and when I inspect:
![screen shot 2016-02-29 at 9 51 55 am](https://cloud.githubusercontent.com/assets/6340292/13398146/0498151c-decb-11e5-862e-4a3261798659.png)
![screen shot 2016-02-29 at 9 54 02 am](https://cloud.githubusercontent.com/assets/6340292/13398148/08081026-decb-11e5-9975-5b5ecedaece6.png)

Any ideas on this one? :space_invader: 

V

**Comment by vivkay** [comment]
…could it perhaps have something to do with the .html files of the .md files that jekyll is auto-generating?
![screen shot 2016-02-29 at 10 03 25 am](https://cloud.githubusercontent.com/assets/6340292/13398311/c52c25f2-decb-11e5-9d8a-a0b4e8eaf69f.png)

**Comment by thomasjbradley** [comment]
Yeah it most likely is those HTML files...
If you delete them from that folder do they come back?

**Comment by vivkay** [comment]
totally resolved it by deleting the HTML files. How bizarre! Thanks!
