### ISSUE TITLE
nested layouts

### ISSUE THREAD

**Issue by vivkay** [vivkay/ffi#38]
Hi @thomasjbradley, 

I'm trying to use jekyll to automatically create blog pages from my md files. I'm using your video tutorial 'advanced nested layouts…' but the page seems to keep breaking somewhere. 

Video:
https://www.youtube.com/watch?v=dUwF_0NRbu8&index=26&list=PLWjCJDeWfDdfVEcLGAfdJn_HXyM4Y7_k-

Basically, I'm using a jekyll loop to generate pages on my blog, which works great. I wrapped my li in an a tag which links to the url of that .md file, and the content come through but the css gets disconnected. 

So this is what I'm seeing for my inside blog page:

![screen shot 2016-03-07 at 8 50 39 am](https://cloud.githubusercontent.com/assets/6340292/13571289/115879aa-e442-11e5-859c-4516a8c2b031.png)

This is my md file
```
---
layout: blog-article
title: "Better Together: Collaborating for Biodiversity and Business"
meta: Fauna & Flora International’s Pippa Howard explains why NGOs, consultancies and other conservationists are joining forces to bring about biodiversity conservation in the private sector.
source: ffi website
category: General, Business & Biodiversity
author: Pippa Howard
image: blog-business.jpg
deck: Fauna & Flora International’s Pippa Howard explains why NGOs, consultancies and other conservationists are joining forces to bring about biodiversity conservation in the private sector.
---

Fauna & Flora International’s Pippa Howard explains why NGOs, consultancies and other conservationists are joining forces to bring about biodiversity conservation in the private sector… (this continues - it's a long article so I cut it here).
```

This is my layout 'blog-article'
```
---
layout: default
---

<div class="grid">
  <div class="unit unit-xs-1-2 island-2">
    <p>{{content}}</p>
  </div>
</div>

```

Any ideas?

**Comment by thomasjbradley** [comment]
Do you have `{{site.baseurl}}` in the CSS file’s `<link>` tag?

**Comment by vivkay** [comment]
um...what is the CSS file's <link> tag? eep!

**Comment by thomasjbradley** [comment]
There's a slash `/` missing right between `{{site.baseurl}}` and `css/` like this:

```
{{site.baseurl}}/css/style.css
```

**Comment by sara-clayton2** [comment]
done
