### ISSUE TITLE
mobile nav wont open 

### ISSUE THREAD

**Issue by sara-clayton2** [vivkay/ffi#47]
Hey Thomas, so for some reason my nav toggle on mobile screens will not open, when on the home screen it opens up but when I click on other links then try open up the mobile nav it won't work. any reason why this is happening ? 

@thomasjbradley

![screen shot 2016-03-08 at 9 10 05 pm](https://cloud.githubusercontent.com/assets/6340308/13623126/35296fa2-e572-11e5-867a-0d986792d5f9.png)
![screen shot 2016-03-08 at 9 09 56 pm](https://cloud.githubusercontent.com/assets/6340308/13623128/353bada2-e572-11e5-8943-01703b39e309.png)

**Comment by thomasjbradley** [comment]
It's another `{{site.baseurl}}` thing—it’s missing from the `<script>` tag here:
https://github.com/vivkay/ffi/blob/gh-pages/_layouts/default.html#L105

**Comment by sara-clayton2** [comment]
thanks!
